package com.revature.daos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.revature.models.Employee;
import com.revature.util.ConnectionUtil;

public class EmployeePostgres implements EmployeeDao {

	@Override
	public Employee createEmployee(Employee em) {
		String sql = "insert into employees (e_name, e_pass) values (?,?) returning employee_id;";
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setString(1, em.getName());
			ps.setString(2, em.getPass());
			
			ResultSet rs = ps.executeQuery(); // return the id generated by the database
			if(rs.next()) {
				em.setId(rs.getInt("employee_id"));
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return em;
	}

	@Override
	public Employee retrieveEmployeeById(int employee_id) {
		String sql = "select * from employees where employee_id = ?;";
		Employee employee = null;
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setInt(1, employee_id); // this refers to the 1st ? in the sql String
			
			ResultSet rs = ps.executeQuery();
			
			if(rs.next()) {
				employee = new Employee();
				employee.setId(rs.getInt("employee_id"));
				employee.setName(rs.getString("e_name"));
				employee.setPass(rs.getString("e_pass"));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return employee;
	}

	@Override
	public List<Employee> retrieveEmployees() {
		String sql = "select * from employees;";
		List<Employee> users = new ArrayList<>();
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			// no user input taken, no need for prepared statement
			Statement s = c.createStatement();
			ResultSet rs = s.executeQuery(sql);
			
			while(rs.next()) {
				// extract each field from rs for each record, map them to a User object and add them to the users arrayliost
				Employee em = new Employee();
				em.setId(rs.getInt("employee_id"));
				em.setName(rs.getString("e_name"));
				em.setPass(rs.getString("e_pass"));
				
				users.add(em);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return users;
	}

	@Override
	public Employee retrieveEmployeeByName(String e_name) {
		String sql = "select * from employees where e_name  = ?;";
		Employee em = null;
		
		try (Connection c = ConnectionUtil.getConnectionFromEnv();){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setString(1, e_name); // this refers to the 1st "?" in the sql string, allows to inject data

			ResultSet rs = ps.executeQuery();
			
			while(rs.next()) {
				em = new Employee();
				em.setId(rs.getInt("employee_id"));
				em.setName(rs.getString("e_name"));
				em.setPass(rs.getString("e_pass"));
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return em;
	}

	@Override
	public boolean updateEmployee(Employee em) {
		String sql = "update employees set e_name = ?, e_pass = ? where employee_id = ?;";
		int rowsChanged = -1;
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setString(1, em.getName());
			ps.setString(2, em.getPass());
			ps.setInt(3, em.getId());
			
			rowsChanged = ps.executeUpdate();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		if(rowsChanged < 1) {
			return false;
		}
		return true;
	}

	@Override
	public boolean deleteEmployeeById(int employee_id) {
		String sql = "delete from employees where employee_id = ?;";
		int rowsChanged = -1;
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setInt(1, employee_id);
			
			rowsChanged = ps.executeUpdate();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		if(rowsChanged < 1) {
			return false;
		}
		return true;
	}

}
