package com.revature.daos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.revature.models.ERS_User_Role;
import com.revature.util.ConnectionUtil;

public class ERS_User_RolePostgres implements ERS_User_RoleDao {

	@Override
	public ERS_User_Role createRole(ERS_User_Role r) {
		String sql = "insert into ers_user_roles (user_role) values (?) returning ers_user_role_id;";
		try (Connection c = ConnectionUtil.getConnectionFromEnv()) {
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setString(1, r.getUser_role());

			ResultSet rs = ps.executeQuery(); // return the id generated by the database
			if (rs.next()) {
				r.setErs_user_role_id(rs.getInt("ers_user_role_id"));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return r;
	}

	public ERS_User_Role retrieveMostRecentRole(Object ers_user_role_id) {
		String sql = "select last_value from ers_user_roles_ers_user_role_id_seq;";
		ERS_User_Role role = null;

		try (Connection c = ConnectionUtil.getConnectionFromEnv()) {
			Statement s = c.createStatement();
			ResultSet rs = s.executeQuery(sql);
			
			while(rs.next()) {
				ERS_User_Role ur = new ERS_User_Role();
				ur.setErs_user_role_id(rs.getInt("last_value"));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return role;
	}
}
