package com.revature.daos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.revature.models.ERS_User_Role;
import com.revature.util.ConnectionUtil;

public class ERS_User_RolePostgres implements ERS_User_RoleDao{

	@Override
	public ERS_User_Role createRole(ERS_User_Role r) {
		String sql = "insert into ers_user_roles (user_role) values (?) returning id;";
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setString(1, r.getRole());
			
			ResultSet rs = ps.executeQuery(); // return the id generated by the database
			if(rs.next()) {
				r.setId(rs.getInt("ers_user_role_id"));
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return r;
	}

}
