package com.revature.daos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.revature.models.ERS_User;
import com.revature.util.ConnectionUtil;

public class ERS_UserPostgres implements ERS_UserDao {

	@Override
	public ERS_User createUser(ERS_User u) {
		String sql = "insert into ers_users (ers_firstname, ers_lastname, ers_username, ers_password, ers_email)"
				+ "values (?,?,?,?,?) returning ers_user_id;";
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setString(1, u.getErs_firstname());
			ps.setString(2, u.getErs_lastname());
			ps.setString(3, u.getErs_username());
			ps.setString(4, u.getErs_password());
			ps.setString(5, u.getErs_email());
			
			ResultSet rs = ps.executeQuery(); // return the id generated by the database
			if(rs.next()) {
				u.setErs_user_id(rs.getInt("ers_user_id"));
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return u;
	}

	@Override
	public ERS_User retrieveUserByUsername(String ers_username) {
		String sql = "select * from ers_users where ers_username  = ?;";
		ERS_User u = null;
		
		try (Connection c = ConnectionUtil.getConnectionFromEnv();){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setString(1, ers_username); // this refers to the 1st "?" in the sql string, allows to inject data

			ResultSet rs = ps.executeQuery();
			
			while(rs.next()) {
				u = new ERS_User();
				u.setErs_user_id(rs.getInt("ers_user_id"));
				u.setErs_firstname(rs.getString("ers_firstname"));
				u.setErs_lastname(rs.getString("ers_lastname"));
				u.setErs_username(rs.getString("ers_username"));
				u.setErs_password(rs.getString("ers_password"));
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return u;
	}

}
